-- Give platform administrators a first-class record while keeping the shared
-- users table as the source for login credentials and session identity.
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  display_name TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS admins_status_created_idx
  ON admins (status, created_at DESC);

-- Preserve access for existing administrator accounts during the transition.
INSERT INTO admins (user_id, display_name)
SELECT id, name
FROM users
WHERE role = 'admin'
ON CONFLICT (user_id) DO NOTHING;
