ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS kyc_status TEXT NOT NULL DEFAULT 'not_started';
ALTER TABLE investors
  ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending';

CREATE TABLE IF NOT EXISTS kyc_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('business', 'investor')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'needs_changes', 'rejected')),
  answers_ciphertext BYTEA NOT NULL,
  answers_iv BYTEA NOT NULL,
  answers_auth_tag BYTEA NOT NULL,
  review_notes TEXT,
  reviewed_by BIGINT REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS kyc_submissions_owner_created_idx
  ON kyc_submissions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS kyc_submissions_status_created_idx
  ON kyc_submissions (status, created_at DESC);

CREATE TABLE IF NOT EXISTS kyc_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL REFERENCES kyc_submissions(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  original_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  ciphertext BYTEA NOT NULL,
  iv BYTEA NOT NULL,
  auth_tag BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS kyc_documents_submission_idx
  ON kyc_documents (submission_id);

CREATE TABLE IF NOT EXISTS kyc_access_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id BIGINT NOT NULL REFERENCES kyc_submissions(id) ON DELETE CASCADE,
  actor_user_id BIGINT NOT NULL REFERENCES users(id),
  action TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS kyc_access_logs_submission_idx
  ON kyc_access_logs (submission_id, created_at DESC);
